project_id = "wkxvruapnvflgykzqtgp"

[functions.simulate-environment]
verify_jwt = false

[functions.generate-recommendations]
verify_jwt = false

[functions.generate-missions]
verify_jwt = false

[functions.generate-advisory]
verify_jwt = false

[functions.reset-rover-batteries]
verify_jwt = false

[functions.test-rover-log]
verify_jwt = false
